#!/usr/bin/env python3
"""Module compiled wth Python3"""

import asyncio
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Async coroutine that collects random number generated by 'async_generator'
    It then returns those numbers as a List of floats.
    Returns: List[float] - A list of randomly generated float numbers.
    """
    return [number async for number in async_generator()]
